# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=100, null=True)),
                ('authorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.authors')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=50, null=True)),
                ('bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.books')),
            ],
        ),
    ]
